# Limpieza de visualizaciones.csv

In [108]:
df_visualizaciones.to_csv("visualizaciones_limpio.csv", index=False)

In [102]:
df_visualizaciones.info()

<class 'pandas.DataFrame'>
RangeIndex: 6000 entries, 0 to 5999
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   visualizacion_id  6000 non-null   int64
 1   user_id           6000 non-null   int64
 2   contenido_id      6000 non-null   int64
 3   fecha             6000 non-null   datetime64[us]
 4   minutos_vistos    6000 non-null   int64
 5   dispositivo       6000 non-null   str
 6   completado        6000 non-null   str
dtypes: datetime64[us](1), int64(4), str(2)
memory usage: 328.3 KB

In [101]:
df_visualizaciones['fecha'] = pd.to_datetime(df_visualizaciones['fecha'], format='mixed')

In [100]:
print(sorted(df_visualizaciones['dispositivo'].unique()))

['Celular', 'PC', 'Smart TV', 'Tablet']

In [99]:
df_visualizaciones.isnull().sum()

visualizacion_id    0
user_id             0
contenido_id        0
fecha               0
minutos_vistos      0
dispositivo         0
completado          0
dtype: int64

In [98]:
df_visualizaciones['completado'] = df_visualizaciones['completado'].fillna('No especificado')

In [97]:
print(sorted(df_visualizaciones['dispositivo'].unique()))

['Celular', 'PC', 'Smart TV', 'Tablet']

In [96]:
correcciones_dispositivo = {
    'pc': 'PC',
    'smart tv': 'Smart TV'
}

df_visualizaciones['dispositivo'] = df_visualizaciones['dispositivo'].replace(correcciones_dispositivo)

In [95]:
print(sorted(df_visualizaciones['dispositivo'].unique()))

['Celular', 'PC', 'Smart TV', 'Tablet', 'pc', 'smart tv']

In [94]:
df_visualizaciones['minutos_vistos'].max()

np.int64(300)

In [93]:
df_visualizaciones['minutos_vistos'].min()

np.int64(0)

In [92]:
df_visualizaciones['minutos_vistos'] = df_visualizaciones['minutos_vistos'].clip(lower=0, upper=300)

In [91]:
print(sorted(df_visualizaciones['completado'].dropna().unique()))

['No', 'Si']

In [90]:
df_visualizaciones['completado'] = df_visualizaciones['completado'].str.strip().str.title()

In [89]:
(df_visualizaciones['minutos_vistos'] > 300).sum()

np.int64(52)

In [88]:
print(sorted(df_visualizaciones['completado'].dropna().unique()))

['No', 'Si', 'no', 'si']

In [87]:
(df_visualizaciones['minutos_vistos'] < 0).sum()

np.int64(120)

In [86]:
df_visualizaciones['minutos_vistos'].max()

np.int64(2860)

In [85]:
df_visualizaciones['minutos_vistos'].min()

np.int64(-1340)

In [84]:
df_visualizaciones.duplicated().sum()

np.int64(0)

In [83]:
df_visualizaciones.isnull().sum()

visualizacion_id       0
user_id                0
contenido_id           0
fecha                  0
minutos_vistos         0
dispositivo            0
completado          1237
dtype: int64

In [82]:
df_visualizaciones.info()

<class 'pandas.DataFrame'>
RangeIndex: 6000 entries, 0 to 5999
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   visualizacion_id  6000 non-null   int64
 1   user_id           6000 non-null   int64
 2   contenido_id      6000 non-null   int64
 3   fecha             6000 non-null   str
 4   minutos_vistos    6000 non-null   int64
 5   dispositivo       6000 non-null   str
 6   completado        4763 non-null   str
dtypes: int64(4), str(3)
memory usage: 328.3 KB

In [81]:
df_visualizaciones = pd.read_csv("visualizaciones.csv")
df_visualizaciones.head()

,visualizacion_id,user_id,contenido_id,fecha,minutos_vistos,dispositivo,completado
0,1,551,80,2023-01-22,52,smart tv,NaN
1,2,237,144,2025-01-11,29,pc,NaN
2,3,194,45,2023-01-16,39,PC,No
3,4,132,77,2024-07-01,32,Smart TV,No
4,5,41,99,2023-07-26,-30,pc,no

# Limpieza de suscripciones.csv

In [107]:
df_suscripciones.to_csv("suscripciones_limpio.csv", index=False)

In [80]:
df_suscripciones.info()

<class 'pandas.DataFrame'>
RangeIndex: 775 entries, 0 to 774
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   suscripcion_id  775 non-null    int64
 1   user_id         775 non-null    int64
 2   plan_id         775 non-null    int64
 3   fecha_inicio    775 non-null    datetime64[us]
 4   fecha_fin       573 non-null    datetime64[us]
 5   motivo_baja     573 non-null    str
 6   metodo_pago     775 non-null    str
dtypes: datetime64[us](2), int64(3), str(2)
memory usage: 42.5 KB

In [79]:
df_suscripciones['fecha_fin'] = pd.to_datetime(df_suscripciones['fecha_fin'], format='mixed')

In [78]:
df_suscripciones['fecha_inicio'] = pd.to_datetime(df_suscripciones['fecha_inicio'], format='mixed')

In [77]:
print(sorted(df_suscripciones['metodo_pago'].unique()))

['Debito Automatico', 'Mercado Pago', 'Tarjeta De Credito']

In [76]:
df_suscripciones['metodo_pago'] = df_suscripciones['metodo_pago'].str.strip().str.title()

In [75]:
print(sorted(df_suscripciones['metodo_pago'].unique()))

['Debito Automatico', 'Mercado Pago', 'Tarjeta de Credito', 'Tarjeta de credito', 'mercado pago', 'tarjeta de credito']

In [74]:
df_suscripciones.isnull().sum()

suscripcion_id      0
user_id             0
plan_id             0
fecha_inicio        0
fecha_fin         202
motivo_baja       202
metodo_pago         0
dtype: int64

In [73]:
df_suscripciones.loc[df_suscripciones['fecha_fin'].notnull(), 'motivo_baja'] = df_suscripciones.loc[df_suscripciones['fecha_fin'].notnull(), 'motivo_baja'].fillna('Motivo no informado')

In [72]:
df_suscripciones[df_suscripciones['fecha_fin'].notnull() & df_suscripciones['motivo_baja'].isnull()]

,suscripcion_id,user_id,plan_id,fecha_inicio,fecha_fin,motivo_baja,metodo_pago
0,1,1,1,2023-02-09,2024-05-04,NaN,Mercado Pago
5,6,4,1,2023-02-23,2024-03-19,NaN,tarjeta de credito
9,10,8,1,2023-01-24,2023-12-20,NaN,tarjeta de credito
27,28,22,2,2023-07-02,2024-08-25,NaN,mercado pago
33,34,27,2,2023-06-25,2025-02-14,NaN,Debito Automatico
...,...,...,...,...,...,...,...
742,743,575,1,2023-04-30,2023-08-28,NaN,tarjeta de credito
754,755,584,1,2023-01-21,2023-08-19,NaN,tarjeta de credito
756,757,586,2,2023-06-25,2024-01-21,NaN,Mercado Pago
766,767,595,3,2023-04-09,2023-05-09,NaN,Mercado Pago
774,775,600,2,2023-04-02,2024-06-25,NaN,Tarjeta de credito

In [71]:
df_suscripciones.duplicated().sum()

np.int64(0)

In [70]:
df_suscripciones.isnull().sum()

suscripcion_id      0
user_id             0
plan_id             0
fecha_inicio        0
fecha_fin         202
motivo_baja       312
metodo_pago         0
dtype: int64

In [69]:
df_suscripciones.info()

<class 'pandas.DataFrame'>
RangeIndex: 775 entries, 0 to 774
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   suscripcion_id  775 non-null    int64
 1   user_id         775 non-null    int64
 2   plan_id         775 non-null    int64
 3   fecha_inicio    775 non-null    str
 4   fecha_fin       573 non-null    str
 5   motivo_baja     463 non-null    str
 6   metodo_pago     775 non-null    str
dtypes: int64(3), str(4)
memory usage: 42.5 KB

In [68]:
df_suscripciones = pd.read_csv("suscripciones.csv")
df_suscripciones.head()

,suscripcion_id,user_id,plan_id,fecha_inicio,fecha_fin,motivo_baja,metodo_pago
0,1,1,1,2023-02-09,2024-05-04,NaN,Mercado Pago
1,2,1,2,2024-07-06,2025-04-02,Precio alto,Tarjeta de Credito
2,3,2,2,2023-04-26,NaN,NaN,Tarjeta de credito
3,4,3,2,2023-03-14,2023-05-13,Motivo no informado,mercado pago
4,5,3,1,2023-07-05,NaN,NaN,Mercado Pago

# Limpieza de resenas.csv

In [106]:
df_resenas.to_csv("resenas_limpio.csv", index=False)

In [67]:
df_resenas.info()

<class 'pandas.DataFrame'>
RangeIndex: 899 entries, 0 to 898
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   resena_id     899 non-null    int64
 1   user_id       899 non-null    int64
 2   contenido_id  899 non-null    int64
 3   puntaje       899 non-null    int64
 4   comentario    899 non-null    str
 5   fecha         899 non-null    datetime64[us]
dtypes: datetime64[us](1), int64(4), str(1)
memory usage: 42.3 KB

In [66]:
df_resenas['puntaje'].min()

np.int64(1)

In [65]:
df_resenas['puntaje'].min()
df_resenas['puntaje'].max()

np.int64(5)

In [64]:
df_resenas['puntaje'] = df_resenas['puntaje'].clip(lower=1, upper=5)

In [63]:
df_resenas[(df_resenas['puntaje'] < 1) | (df_resenas['puntaje'] > 5)]

,resena_id,user_id,contenido_id,puntaje,comentario,fecha
54,55,372,116,-1,No me gusto para nada,2023-09-30
66,67,59,66,0,No la recomiendo,2025-11-28
76,77,47,31,-1,Muy lenta,2024-10-02
113,114,46,131,6,Muy entretenida,2026-02-08
117,118,243,34,6,La recomiendo totalmente,2026-02-21
131,132,240,46,6,Excelente produccion,2024-10-26
180,181,319,137,0,Se hace repetitiva,2023-07-08
217,218,131,7,6,La recomiendo totalmente,2026-03-28
392,393,79,128,6,La recomiendo totalmente,2025-05-29
406,407,216,9,-1,Se hace repetitiva,2023-06-01
466,467,405,91,6,Un imperdible,2023-11-13
517,518,65,3,6,La recomiendo totalmente,2024-12-04
533,534,260,90,6,Me encanto,2025-08-15
571,572,225,146,-1,Se hace repetitiva,2025-08-30
607,608,222,63,-1,Muy lenta,2026-05-08
655,656,13,29,0,No la recomiendo,2024-03-24
709,710,201,103,-1,No me gusto para nada,2023-08-25
725,726,458,73,0,Muy lenta,2024-11-22
804,805,330,128,6,Me encanto,2023-06-27
818,819,363,113,6,Me encanto,2024-01-31
830,831,26,139,0,Esperaba mas,2023-04-12
868,869,507,103,6,La recomiendo totalmente,2023-03-23
894,895,584,28,-1,Se hace repetitiva,2023-09-13

In [62]:
df_resenas['puntaje'].max()

np.int64(6)

In [61]:
df_resenas['puntaje'].min()

np.int64(-1)

In [60]:
df_resenas['fecha'] = pd.to_datetime(df_resenas['fecha'], format='mixed')

In [59]:
df_resenas.duplicated().sum()

np.int64(0)

In [58]:
df_resenas.isnull().sum()

resena_id       0
user_id         0
contenido_id    0
puntaje         0
comentario      0
fecha           0
dtype: int64

In [57]:
df_resenas.info()

<class 'pandas.DataFrame'>
RangeIndex: 899 entries, 0 to 898
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   resena_id     899 non-null    int64
 1   user_id       899 non-null    int64
 2   contenido_id  899 non-null    int64
 3   puntaje       899 non-null    int64
 4   comentario    899 non-null    str
 5   fecha         899 non-null    str
dtypes: int64(4), str(2)
memory usage: 42.3 KB

In [56]:
df_resenas = pd.read_csv("resenas.csv")
df_resenas.head()

   resena_id  user_id  contenido_id  puntaje            comentario       fecha
0          1      556            69        1      No la recomiendo  2026-02-19
1          2      515           158        4       Muy entretenida  2024-09-26
2          3      551            92        4       Muy entretenida  2025-02-26
3          4      165           106        2             Muy lenta  2024-08-27
4          5      289           139        4  Excelente produccion  2023-06-29

# Limpieza de planes.csv

In [105]:
df_planes.to_csv("planes_limpio.csv", index=False)

In [55]:
df_planes.duplicated().sum()

np.int64(0)

In [54]:
df_planes.isnull().sum()

plan_id                  0
nombre_plan              0
precio_mensual           0
pantallas_simultaneas    0
calidad_video            0
dtype: int64

In [53]:
df_planes.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 5 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   plan_id                4 non-null      int64
 1   nombre_plan            4 non-null      str
 2   precio_mensual         4 non-null      int64
 3   pantallas_simultaneas  4 non-null      int64
 4   calidad_video          4 non-null      str
dtypes: int64(3), str(2)
memory usage: 292.0 bytes

In [52]:
df_planes = pd.read_csv("planes.csv")
df_planes.head()

   plan_id nombre_plan  precio_mensual  pantallas_simultaneas calidad_video
0        1      Basico            1490                      1            SD
1        2    Estandar            2490                      2            HD
2        3     Premium            3490                      4            4K
3        4    Familiar            3990                      6            4K

# Limpieza de pagos.csv

In [104]:
df_pagos.to_csv("pagos_limpio.csv", index=False)

In [51]:
df_pagos.info()

<class 'pandas.DataFrame'>
Index: 12720 entries, 0 to 12722
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   pago_id         12720 non-null  int64
 1   suscripcion_id  12720 non-null  int64
 2   fecha_pago      12720 non-null  datetime64[us]
 3   monto           12720 non-null  float64
 4   estado          12720 non-null  str
dtypes: datetime64[us](1), float64(1), int64(2), str(1)
memory usage: 596.2 KB

In [50]:
df_pagos['fecha_pago'] = pd.to_datetime(df_pagos['fecha_pago'], format='mixed')

In [49]:
df_pagos.info()

<class 'pandas.DataFrame'>
Index: 12720 entries, 0 to 12722
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   pago_id         12720 non-null  int64
 1   suscripcion_id  12720 non-null  int64
 2   fecha_pago      12720 non-null  str
 3   monto           12720 non-null  float64
 4   estado          12720 non-null  str
dtypes: float64(1), int64(2), str(2)
memory usage: 596.2 KB

In [48]:
df_pagos.isnull().sum()

pago_id           0
suscripcion_id    0
fecha_pago        0
monto             0
estado            0
dtype: int64

In [47]:
df_pagos = df_pagos.dropna(subset=['monto'])

In [46]:
df_pagos[df_pagos['monto'].isnull()]

      pago_id  suscripcion_id  fecha_pago  monto   estado
2345     2346             143  2023-02-17    NaN  Exitoso
4215     4216             269  2023-12-23    NaN  Exitoso
4502     4503             290  2023-05-18    NaN  Exitoso

In [45]:
df_pagos.isnull().sum()

pago_id           0
suscripcion_id    0
fecha_pago        0
monto             3
estado            0
dtype: int64

In [44]:
df_pagos['monto'] = df_pagos.groupby('suscripcion_id')['monto'].transform(lambda x: x.fillna(x.median()))

In [43]:
df_pagos[df_pagos['suscripcion_id'] == 1]['monto']

0     1490.0
1     1490.0
2     1490.0
3     1490.0
4     1490.0
5        NaN
6     1490.0
7     1490.0
8     1490.0
9     1490.0
10    1490.0
11    1490.0
12    1490.0
13    1490.0
14    1490.0
Name: monto, dtype: float64

In [42]:
df_pagos[df_pagos['monto'].isnull()]['estado'].value_counts()

estado
Exitoso    506
Fallido     30
Name: count, dtype: int64

In [41]:
df_pagos.info()

<class 'pandas.DataFrame'>
RangeIndex: 12723 entries, 0 to 12722
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   pago_id         12723 non-null  int64
 1   suscripcion_id  12723 non-null  int64
 2   fecha_pago      12723 non-null  str
 3   monto           12187 non-null  float64
 4   estado          12723 non-null  str
dtypes: float64(1), int64(2), str(2)
memory usage: 497.1 KB

In [40]:
df_pagos['monto'] = df_pagos['monto'].replace('[\$,]', '', regex=True)
df_pagos['monto'] = df_pagos['monto'].astype(float)

<>:1: SyntaxWarning: "\$" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\$"? A raw string is also an option.
<>:1: SyntaxWarning: "\$" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\$"? A raw string is also an option.
C:\Users\estef\AppData\Local\Temp\ipykernel_22156\2008922408.py:1: SyntaxWarning: "\$" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\$"? A raw string is also an option.
  df_pagos['monto'] = df_pagos['monto'].replace('[\$,]', '', regex=True)

In [39]:
df_pagos.isnull().sum()

pago_id             0
suscripcion_id      0
fecha_pago          0
monto             536
estado              0
dtype: int64

In [38]:
df_pagos.isnull().sum()
df_pagos.duplicated().sum()

np.int64(0)

In [37]:

df_pagos.info()
df_pagos.isnull().sum()
df_pagos.duplicated().sum()

<class 'pandas.DataFrame'>
RangeIndex: 12723 entries, 0 to 12722
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   pago_id         12723 non-null  int64
 1   suscripcion_id  12723 non-null  int64
 2   fecha_pago      12723 non-null  str
 3   monto           12187 non-null  str
 4   estado          12723 non-null  str
dtypes: int64(2), str(3)
memory usage: 497.1 KB

np.int64(0)

In [36]:
df_pagos = pd.read_csv("pagos.csv")
df_pagos.head()

   pago_id  suscripcion_id  fecha_pago      monto   estado
0        1               1  09/02/2023       1490  Exitoso
1        2               1  2023-03-11  $1,490.00  Exitoso
2        3               1  10/04/2023  $1,490.00  Exitoso
3        4               1  2023-05-10       1490  Exitoso
4        5               1  09/06/2023       1490  Exitoso

# Limpieza de contenido.csv

In [103]:
df_contenido.to_csv("contenido_limpio.csv", index=False)

In [35]:
df_contenido['anio_lanzamiento'].min()

np.int64(1990)

In [34]:
df_contenido['anio_lanzamiento'].min()

df_contenido['anio_lanzamiento'].max()

np.int64(2026)

In [33]:
print(sorted(df_contenido['tipo'].unique()))
print(sorted(df_contenido['genero'].unique()))
print(sorted(df_contenido['rating_edad'].unique()))

['Pelicula', 'Serie']
['Accion', 'Animacion', 'Ciencia Ficcion', 'Comedia', 'Documental', 'Drama', 'Romance', 'Sin especificar', 'Terror', 'Thriller']
['+13', '+16', '+18', 'ATP']

In [32]:
df_contenido.duplicated().sum()

np.int64(0)

In [31]:
df_contenido.isnull().sum()

contenido_id         0
titulo               0
tipo                 0
genero               0
anio_lanzamiento     0
duracion_min        72
temporadas          88
rating_edad          0
dtype: int64

In [30]:
df_contenido['genero'] = df_contenido['genero'].fillna('Sin especificar')

In [29]:
df_contenido[df_contenido['genero'].isnull()]

,contenido_id,titulo,tipo,genero,anio_lanzamiento,duracion_min,temporadas,rating_edad
59,60,Titulo Original 60,Serie,NaN,2009,NaN,1.0,ATP
88,89,Titulo Original 89,Pelicula,NaN,1992,91.0,NaN,+16
92,93,Titulo Original 93,Pelicula,NaN,2010,79.0,NaN,+18
98,99,Titulo Original 99,Pelicula,NaN,2026,126.0,NaN,+13
140,141,Titulo Original 141,Serie,NaN,2006,NaN,4.0,+18

In [28]:
df_contenido.isnull().sum()

df_contenido.duplicated().sum()

np.int64(0)

In [27]:
df_contenido.info()

df_contenido.isnull().sum()

df_contenido.duplicated().sum()

<class 'pandas.DataFrame'>
RangeIndex: 160 entries, 0 to 159
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   contenido_id      160 non-null    int64
 1   titulo            160 non-null    str
 2   tipo              160 non-null    str
 3   genero            155 non-null    str
 4   anio_lanzamiento  160 non-null    int64
 5   duracion_min      88 non-null     float64
 6   temporadas        72 non-null     float64
 7   rating_edad       160 non-null    str
dtypes: float64(2), int64(2), str(4)
memory usage: 10.1 KB

np.int64(0)

In [26]:
df_contenido = pd.read_csv("contenido.csv")
df_contenido.head()

,contenido_id,titulo,tipo,genero,anio_lanzamiento,duracion_min,temporadas,rating_edad
0,1,Titulo Original 1,Serie,Romance,2019,NaN,1.0,ATP
1,2,Titulo Original 2,Pelicula,Ciencia Ficcion,1992,112.0,NaN,+18
2,3,Titulo Original 3,Serie,Ciencia Ficcion,2026,NaN,4.0,ATP
3,4,Titulo Original 4,Serie,Drama,2022,NaN,6.0,ATP
4,5,Titulo Original 5,Pelicula,Drama,2013,121.0,NaN,+13

# Limpieza de usuarios.csv

In [109]:
df_usuarios.to_csv("usuarios_limpio.csv", index=False)

In [25]:
df_usuarios.info()

<class 'pandas.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   user_id                600 non-null    int64
 1   nombre                 600 non-null    str
 2   apellido               600 non-null    str
 3   email                  600 non-null    str
 4   pais                   600 non-null    str
 5   edad                   600 non-null    float64
 6   fecha_registro         600 non-null    datetime64[us]
 7   dispositivo_principal  600 non-null    str
dtypes: datetime64[us](1), float64(1), int64(1), str(5)
memory usage: 37.6 KB

In [24]:
df_usuarios['nombre'] = df_usuarios['nombre'].str.strip()
df_usuarios['apellido'] = df_usuarios['apellido'].str.strip()

In [23]:
print(sorted(df_usuarios['dispositivo_principal'].unique()))

['Celular', 'PC', 'Smart TV', 'Tablet']

In [22]:
correcciones_dispositivo = {
    'celular': 'Celular',
    'pc': 'PC',
    'smart tv': 'Smart TV'
}

df_usuarios['dispositivo_principal'] = df_usuarios['dispositivo_principal'].replace(correcciones_dispositivo)

In [21]:
print(sorted(df_usuarios['dispositivo_principal'].unique()))

['Celular', 'PC', 'Smart TV', 'Tablet', 'celular', 'pc', 'smart tv']

In [20]:
df_usuarios[~df_usuarios['email'].str.contains('@')]

Empty DataFrame
Columns: [user_id, nombre, apellido, email, pais, edad, fecha_registro, dispositivo_principal]
Index: []

In [19]:
df_usuarios['email'] = df_usuarios['email'].str.strip().str.lower()

In [18]:
print(sorted(df_usuarios['pais'].unique()))

['Argentina', 'Bolivia', 'Chile', 'Colombia', 'México', 'Paraguay', 'Perú', 'Uruguay']

In [17]:
correcciones_pais = {
    'Arg.': 'Argentina',
    'Mexico': 'México',
    'Peru': 'Perú'
}

df_usuarios['pais'] = df_usuarios['pais'].replace(correcciones_pais)

In [16]:
print(sorted(df_usuarios['pais'].unique()))

['Arg.', 'Argentina', 'Bolivia', 'Chile', 'Colombia', 'Mexico', 'México', 'Paraguay', 'Peru', 'Perú', 'Uruguay']

In [15]:
df_usuarios['pais'].unique()

<StringArray>
['Argentina',   'Bolivia',    'México',     'Chile',  'Paraguay',   'Uruguay',
    'Mexico',      'Arg.',  'Colombia',      'Peru',      'Perú']
Length: 11, dtype: str

In [14]:
df_usuarios['pais'] = df_usuarios['pais'].str.strip().str.title()

In [13]:
df_usuarios['pais'].unique()

<StringArray>
['Argentina',   'Bolivia',    'México',     'Chile', 'ARGENTINA',  'Paraguay',
   'Uruguay', 'argentina',    'Mexico',      'Arg.',  'Colombia',    'mexico',
      'Peru',      'Perú',      'peru']
Length: 15, dtype: str

In [12]:
df_usuarios.info()

<class 'pandas.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   user_id                600 non-null    int64
 1   nombre                 600 non-null    str
 2   apellido               600 non-null    str
 3   email                  600 non-null    str
 4   pais                   600 non-null    str
 5   edad                   600 non-null    float64
 6   fecha_registro         600 non-null    datetime64[us]
 7   dispositivo_principal  600 non-null    str
dtypes: datetime64[us](1), float64(1), int64(1), str(5)
memory usage: 37.6 KB

In [11]:
df_usuarios['fecha_registro'] = pd.to_datetime(df_usuarios['fecha_registro'], format='mixed')

In [9]:
print(mediana_edad)

44.0

In [8]:
df_usuarios.isnull().sum()

user_id                  0
nombre                   0
apellido                 0
email                    0
pais                     0
edad                     0
fecha_registro           0
dispositivo_principal    0
dtype: int64

In [7]:
mediana_edad = df_usuarios['edad'].median()
df_usuarios['edad'] = df_usuarios['edad'].fillna(mediana_edad)

In [6]:
df_usuarios.duplicated().sum()

np.int64(0)

In [5]:
df_usuarios = df_usuarios.drop_duplicates()

In [4]:
df_usuarios.duplicated().sum()

np.int64(8)

In [3]:
df_usuarios.isnull().sum()

user_id                   0
nombre                    0
apellido                  0
email                     0
pais                      0
edad                     53
fecha_registro            0
dispositivo_principal     0
dtype: int64

In [2]:
df_usuarios.info()

<class 'pandas.DataFrame'>
RangeIndex: 608 entries, 0 to 607
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   user_id                608 non-null    int64
 1   nombre                 608 non-null    str
 2   apellido               608 non-null    str
 3   email                  608 non-null    str
 4   pais                   608 non-null    str
 5   edad                   555 non-null    float64
 6   fecha_registro         608 non-null    str
 7   dispositivo_principal  608 non-null    str
dtypes: float64(1), int64(1), str(6)
memory usage: 38.1 KB

In [1]:
import pandas as pd

df_usuarios = pd.read_csv("usuarios.csv")
df_usuarios.head()

,user_id,nombre,apellido,email,pais,edad,fecha_registro,dispositivo_principal
0,1,Lucas,Gomez,Lucas.Gomez1@yahoo.com.ar,Argentina,NaN,24/04/2026,Smart TV
1,2,Martina,Sosa,Martina.Sosa2@gmail.com,Bolivia,67.0,27/03/2024,pc
2,3,Sofia,Martinez,Sofia.Martinez3@outlook.com,México,44.0,2023-07-29,Celular
3,4,Santiago,Molina,Santiago.Molina4@yahoo.com.ar,Chile,30.0,11-06-2023,PC
4,5,Ignacio,Ruiz,Ignacio.Ruiz5@hotmail.com,ARGENTINA,58.0,2023-06-13,celular